#!/usr/bin/env bash
set -e

a='eigen-eigen-b30b87236a1b'
gz="${a}.tar.gz"
url='https://bitbucket.org/eigen/eigen/get/3.2.7.tar.gz'

SRCDIR="$(readlink -f "$(dirname "$0")" )"
cd "$SRCDIR"

# specifically use -o instead of >
# because cygwin/msys will attempt to convert EOLs
# which is obviously invalid for a binary file
[ -s "$gz" ] || curl -LSs --cacert cacert.pem "$url" -o "$gz"
tar xzf "$gz"
[ -d Eigen ] && rm -r Eigen
mv "$a/Eigen" Eigen
rm -r "$a"
