#!/usr/bin/env bash
set -e
set -u

pp_include="#include \"$1\""
out="$2"
template="$3"

(cat "$template" | while read -r; do
    case "$REPLY" in

    '//#INCLUDE') echo "$pp_include" ;;

    *) echo -E "$REPLY" ;;
    esac
done) > "$out"
